os:
  - linux
  - osx

sudo: false

dist: trusty

before_install:
#  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; sudo apt-get install -y gfortran ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh; fi

#  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update ; fi 
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then wget https://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
#  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then wget https://github.com/UV-CDAT/uvcdat/releases/download/v2.4.1/gfortran-4.9.2-Mac.tar.gz -O ~/gfortran-4.9.2-Mac.tar.gz ; pushd / ; sudo tar xzvf ~/gfortran-4.9.2-Mac.tar.gz ; popd ; fi
  - export PATH="$HOME/miniconda/bin:$PATH"
  - export PREFIX="$HOME/miniconda"
  - export UDUNITS2_XML_PATH=$HOME/miniconda/share/udunits/udunits2.xml
  - export UVCDAT_ANONYMOUS_LOG=no
  - bash miniconda.sh -b -p $HOME/miniconda
  - conda config --set always_yes yes --set changeps1 no
  - conda update -y -q conda
  - conda install openssl=1.0.2d
  - conda install cdms2 -c uvcdat/label/nightly -c uvcdat
  - conda install udunits2 -c uvcdat/label/nightly  -c uvcdat
  - conda install gcc 

install:
    - git clone https://github.com/PCMDI/cmip6-cmor-tables 
    - ln -s cmip6-cmor-tables/Tables Tables
    - ./configure --prefix=$PREFIX --with-python --with-uuid=$PREFIX --with-udunits2=$PREFIX --with-netcdf=$PREFIX  
    - make install 

script: python run_tests.py

